export const ERRORS = {
    GENERIC_ERROR: "Something unexpected has occured. Please try again later.",
    ACCOUNT_ALREADY_EXISTS: "You already have an account!",
    ACCOUNT_DOES_NOT_EXIST: "You do not have an account!",
    ACCOUNT_CANNOT_CREATE: "Your account couldn't be created. Please try again later.",
    ACCOUNT_CANNOT_RETRIEVE: "This account does not exist!",
    BALANCE_CANNOT_RETRIEVE: "There is no balance to show.",
    INPUT_INVALID_AMOUNT: "Please input a valid amount!",
    SUPPLY_WILL_BE_EXCEEDED: "The max supply has been reached!",
    TRANSACTION_AMOUNT_INVALID: "You do not have enough currency!",
    TRANSACTION_CANNON_TRANSFER_TO_SELF: "You cannot transfer to yourself!",
    TRANSACTION_CANNOT_SEND_ZERO: "You can't send nothing!",
    LEADERBOARD_CANNOT_HAVE_MULTIPLE: "Don't have more than one leaderboard open!",
    TRANSACTION_LIST_CANNOT_HAVE_MULTIPLE: "Don't have more than one transaction list open!",
    TRANSACTION_VIEW_CANNOT_RETRIEVE: "This transaction doesn't exist!",
}